### ISSUE TITLE
Deprecation messages

### ISSUE THREAD

**Issue by gingermusketeer** [octokit/request-error.js#206]
I am using a tool called oclif to build a CLI and this tool inspects errors that are thrown to see how they should be shown to the user. Unfortunately this is triggering some deprecation warnings from `request-error`.

The code that is causing the deprecation is `const shouldPrint = !(err.code === 'EEXIT');` and the logged message is 
```
Deprecation: [@octokit/request-error] `error.code` is deprecated, use `error.status`.
```

Is there anyway to avoid seeing these deprecation messages?

**Comment by gr2m** [comment]
Hmm the error will go away once we release a breaking version. But if you like we could check if `error.code` is a number between 100 and 599, and only log the deprecation message in that case? I'd accept a pull request if you are up to it

**Comment by gingermusketeer** [comment]
@gr2m How long do you think this deprecation error will be in place for?

I don't think adding a check would help as the error code in my case is 401. The oclif framework is calling the `.error` method to check if it is some other kind of error. I think having an option to disable the deprecation or opt in to the new behaviour would be the only way forward. What do you think?

**Comment by gr2m** [comment]
> How long do you think this deprecation error will be in place for?

I don't know. We will definitely have a breaking change coming this year

> I think having an option to disable the deprecation or opt in to the new behaviour would be the only way forward

That would require a lot of changes in `@octokit/*` packages in order to pass through that option, it's too much of an edge case for that, sorry

**Comment by gingermusketeer** [comment]
@gr2m What about an API within this package that I can call directly? Thinking something like:
```js
import {disableDeprecationMessages} from "@oktokit/error"
disableDeprecationMessages()
```

**Comment by gr2m** [comment]
no sorry, I won't add any code to `@error/code` for this particular case, it's just not common enough.

When you do your check 

```js
const shouldPrint = !(err.code === 'EEXIT');
```

maybe add a check above such as 

```js
const isOctokitRequestError = err.name === 'HttpError' && "status" in err
const shouldPrint = !isOctokitRequestError && !(err.code === 'EEXIT');
```

**Comment by gingermusketeer** [comment]
The code you suggested won't work for me as the it is inside a module that I depend on and not code I maintain. Thanks for the feedback however.

**Comment by gingermusketeer** [comment]
Found a way around this:
```js
/* Octokit monkey patch to silence un-fixable deprecation warnings */
import { Deprecation } from "deprecation";
const oldWarn = console.warn;
console.warn = (...args: any[]) => {
  const isDeprecation = args.some((arg) => arg instanceof Deprecation);
  if (isDeprecation) {
    // Silence is golden.
    return;
  }
  oldWarn.apply(console, args);
};
/* End of monkey patch */
```

**Comment by till** [comment]
@gr2m I npm installed'd yesterday, and keep getting these errors. This is among the first Google results. Any update as to how to get rid off these errors?

**Comment by gr2m** [comment]
Right above you: https://github.com/octokit/request-error.js/issues/206#issuecomment-984507799

**Comment by till** [comment]
That's still the only way? Guess I was wondering why the lib I installed yesterday throws so many notices already.

I am just using request.js. And that seems like an odd user experience. Especially since nothing shows up in `npm outdated`?

**Comment by wolfy1339** [comment]
Next major release will get that cleaned up

**Comment by iomarcovalente** [comment]
I guess that wasn't cleaned up in the "next major release" as I am still seeing this issue

**Comment by wolfy1339** [comment]
This upcoming major release, which is in the works actually removes the deprecated code.

See #401

**Comment by till** [comment]
@wolfy1339 Do you want to reopen this ticket until it is fixed? 🫣
