### ISSUE TITLE
NPM package missing dist files

### ISSUE THREAD

**Issue by wolfy1339** [octokit/request-error.js#337]
### What happened?

Only `dist-node` seems to be included in the release, which means there are no types

### Versions

V4.0.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
See https://github.com/octokit/octokit.js/issues/2464#issuecomment-1571206986

**Comment by kfcampbell** [comment]
@wolfy1339 I can help roll out esbuild. Once [oauth-authorization-url.js](https://github.com/octokit/oauth-authorization-url.js/pull/279) has been confirmed to fix the problem, I can replicate that fix across the other 22 instances I see in octokit-owned orgs.
