### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by JoshuaAYoung** [octokit/request-error.js#345]
### What happened?

Request-error is a dependency for something in Lerna (guessing with latest version of request-error), which 6 hours ago was working with Node 14. Lerna now requires Node 18 because of your latest release. I didn't see anything in the release notes about a breaking change like this. Guessing millions of Lerna users are going to be affected here. Will also reach out to Lerna folks and let them know to freeze the version if they can, but just so you all are aware.

### Versions

@octokit/request-error@4.0.2, Node 14.18.3

### Relevant log output

```shell
Run yarn global add lerna
yarn global v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
error @octokit/request-error@4.0.2: The engine "node" is incompatible with this module. Expected version ">= 18". Got "14.18.3"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
Error: Process completed with exit code 1.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
This has been fixed. 
Another user was experiencing the same bug, and I published a fix reverting those changes

**Comment by JoshuaAYoung** [comment]
Thank you! Wow with the quickness.
