### ISSUE TITLE
[BUG]: Typechecking fails for external code with `exactOptionalPropertyTypes: true`

### ISSUE THREAD

**Issue by ammubhave** [octokit/request-error.js#461]
### What happened?

When typescript is used with the option `exactOptionalPropertyTypes: true`, most code that consumes this library fails to typecheck if `undefined` is passed in for the response value.

All optional properties must have explicit `| undefined` in their type definitions.

### Versions

all

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
Are you explicitly passing `undefined` or defining the value at all?

It would be nice to enable this option ourselves across all Octokit repos.

**Comment by oscard0m** [comment]
> Are you explicitly passing `undefined` or defining the value at all?
> 
> It would be nice to enable this option ourselves across all Octokit repos.

I would be happy to give it a try to this. After trying to read a bit about this I got this blog post where it gives good points to enabling this option in out TS Config.

@wolfy1339 would it be ok if I give it a try? If yes, I will create an issue in https://github.com/octokit/tsconfig and we can discuss the plan there.

**Comment by wolfy1339** [comment]
Sure, go ahead
