### ISSUE TITLE
[Bug]New version 1.0.3 lack main entry point

### ISSUE THREAD

**Issue by Joker-Jelly** [octokit/request-error.js#8]
unpkg: 
Not found: main file "index" in package @octokit/request-error@1.0.3

**Comment by JakeGinnivan** [comment]
Yeah, this has busted `npx semantic-release` for me, I suggest hiding the 1.0.3 release

**Comment by gr2m** [comment]
Sorry for that, something went boo boo, I’ve set 1.0.1 to latest, update your lock files

```
$ npm info @octokit/request-error version
1.0.1
```

**Comment by Joker-Jelly** [comment]
Thanks, I already see it restore

**Comment by gr2m** [comment]
fixed via 1.0.4, sorry again :(

**Comment by JakeGinnivan** [comment]
Appreciate the quick turn around @gr2m!
